import aigcbenchPreview from '../assets/aigcbench_preview.svg';
import dualsgPreview from '../assets/dualsg_preview.svg';
import ecgExpertQAPreview from '../assets/ecg_expert_qa_preview.svg';
import folioSpacePreview from '../assets/folio_space.gif';
import kairosPreview from '../assets/kairos_preview.svg';
import okwPreview from '../assets/okw_preview.svg';
import probingMemesPreview from '../assets/probing_memes_preview.svg';
import timemosaicPreview from '../assets/timemosaic_preview.svg';
import type { Project } from '../types/project';
import { SLIDE_IDS } from './slideIds';

export const projectsData: Project[] = [
  {
    id: SLIDE_IDS.ProbingLLMs,
    name: 'Probing Memes in LLMs',
    title: 'Probing Memes in LLMs: A Paradigm for the Entangled Evaluation World',
    preview: probingMemesPreview,
    position: { x: 1500, y: 0, z: 0, rotateY: 0 },
    description:
      'Conceptualizes Large Language Models as composed of "memes" (cultural genes) and introduces the Probing Memes paradigm for fine-grained, population-level evaluation of model behavioral traits.',
    tech: ['LLM', 'Evaluation', 'Meme Theory'],
    links: [
      {
        type: 'demo',
        url: 'https://arxiv.org/abs/2603.04408',
        text: 'ArXiv Paper',
      },
      {
        type: 'code',
        url: '',
        text: 'Github',
        githubRepo: '[NO_GITHUB_FOUND]',
      },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.ECG,
    name: 'ECG-Expert-QA',
    title: 'ECG-Expert-QA: A Benchmark for Evaluating Medical Large Language Models in ECG',
    preview: ecgExpertQAPreview,
    position: { x: 1200, y: 800, z: 200, rotateY: 30 },
    description:
      'A comprehensive benchmark for evaluating medical LLMs in ECG interpretation, featuring multi-turn QA, cross-modal clinical reasoning, and ethical evaluation standards.',
    tech: ['Medical AI', 'ECG', 'LLM Benchmark'],
    links: [
      {
        type: 'demo',
        url: 'https://ieeexplore.ieee.org/document/11356744',
        text: 'BIBM 2025 Paper',
      },
      {
        type: 'code',
        url: 'https://github.com/Zaozzz/ECG-Expert-QA',
        text: 'Github',
        githubRepo: 'Zaozzz/ECG-Expert-QA',
      },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.DualSG,
    name: 'DualSG',
    title: 'DualSG: A Dual-Stream Explicit Semantic-Guided Multivariate Time Series Forecasting Framework',
    preview: dualsgPreview,
    position: { x: 0, y: 1500, z: 400, rotateY: 90 },
    description:
      'A novel dual-stream framework that decouples numerical modeling from semantic reasoning, using LLMs as explicit semantic guides to refine time series forecasts.',
    tech: ['Time Series', 'LLM', 'Forecasting'],
    links: [
      {
        type: 'demo',
        url: 'https://arxiv.org/abs/2507.21830',
        text: 'ArXiv Paper',
      },
      {
        type: 'code',
        url: 'https://github.com/BenchCouncil/DualSG',
        text: 'Github',
        githubRepo: 'BenchCouncil/DualSG',
      },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.KAIROS,
    name: 'KAIROS',
    title: 'KAIROS: Unified Training for Universal Non-Autoregressive Time Series Forecasting',
    preview: kairosPreview,
    position: { x: -1060, y: 1060, z: 600, rotateY: 135 },
    description:
      'A high-performance non-autoregressive framework for universal time series forecasting that models segment-level multi-peak distributions to avoid error accumulation.',
    tech: ['Time Series', 'Foundation Model', 'Forecasting'],
    links: [
      {
        type: 'demo',
        url: 'https://arxiv.org/abs/2510.02084',
        text: 'ArXiv Paper',
      },
      {
        type: 'code',
        url: 'https://github.com/Day333/Kairos',
        text: 'Github',
        githubRepo: 'Day333/Kairos',
      },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.TimeMosaic,
    name: 'TimeMosaic',
    title: 'TimeMosaic: Temporal Heterogeneity Guided Time Series Forecasting via Adaptive Granularity Patch and Segment-wise Decoding',
    preview: timemosaicPreview,
    position: { x: -1500, y: 0, z: 800, rotateY: 180 },
    description:
      'Addresses temporal heterogeneity in time series forecasting using adaptive patch embedding and segment-wise decoding to adjust granularity based on local information density.',
    tech: ['Time Series', 'Adaptive Granularity', 'Forecasting'],
    links: [
      {
        type: 'demo',
        url: 'https://arxiv.org/abs/2509.19406',
        text: 'ArXiv Paper',
      },
      {
        type: 'code',
        url: '',
        text: 'Github',
        githubRepo: '[NO_GITHUB_FOUND]',
      },
    ],
    layout: 'standard',
  },
  {
    id: SLIDE_IDS.AIGCBench,
    name: 'AIGCBench',
    title: 'AIGCBench: Comprehensive Evaluation of Image-to-Video Content Generated by AI',
    preview: aigcbenchPreview,
    position: { x: -1060, y: -1060, z: 1000, rotateY: 225 },
    description:
      'A comprehensive and scalable benchmark for evaluating AI-generated video content, focusing on image-to-video generation across four crucial dimensions including motion and quality.',
    tech: ['AIGC', 'Video Generation', 'Benchmark'],
    links: [
      {
        type: 'demo',
        url: 'https://arxiv.org/abs/2401.01651',
        text: 'ArXiv Paper',
      },
      {
        type: 'code',
        url: 'https://github.com/BenchCouncil/AIGCBench',
        text: 'Github',
        githubRepo: 'BenchCouncil/AIGCBench',
      },
    ],
    layout: 'reverse',
  },
  {
    id: SLIDE_IDS.OKW,
    name: 'OKW',
    title: 'Placeholder for OKW',
    preview: okwPreview,
    position: { x: 0, y: -1500, z: 1200, rotateY: 270 },
    description: 'This is a placeholder for OKW. Please fill in the details.',
    tech: ['Placeholder'],
    links: [
      {
        type: 'demo',
        url: '',
        text: 'Learn More',
      },
    ],
    layout: 'reverse',
    // layout: 'standard', // Wait, previous was reverse, keep consistent.
  },
  {
    id: SLIDE_IDS.PROJECTS,
    name: 'FolioSpace',
    title: 'FolioSpace: A Gamified 3D First-Person Portfolio Gallery',
    preview: folioSpacePreview,
    position: { x: 1060, y: -1060, z: 1400, rotateY: 315 },
    description:
      'A modern and elegant personal portfolio website with smooth animations and responsive design, built with Vue 3 and impress.js.',
    tech: ['Vue 3', 'TypeScript', '3D Graphics'],
    links: [
      {
        type: 'demo',
        url: 'https://sammie.vip/projects',
        text: 'Live Demo',
      },
      {
        type: 'code',
        url: 'https://github.com/szysammie/FolioSpace',
        text: 'Github',
        githubRepo: 'szysammie/FolioSpace',
      },
    ],
    layout: 'standard',
  },
];

export const mapData = [
  {
    id: SLIDE_IDS.TITLE,
    name: 'Introduction',
    icon: 'fas fa-home',
  },
  {
    id: SLIDE_IDS.ProbingLLMs,
    name: 'ProbingLLMs',
    icon: 'fas fa-brain',
  },
  {
    id: SLIDE_IDS.ECG,
    name: 'ECG-Expert-QA',
    icon: 'fas fa-heartbeat',
  },
  {
    id: SLIDE_IDS.DualSG,
    name: 'DualSG',
    icon: 'fas fa-project-diagram',
  },
  {
    id: SLIDE_IDS.KAIROS,
    name: 'KAIROS',
    icon: 'fas fa-rocket',
  },
  {
    id: SLIDE_IDS.TimeMosaic,
    name: 'TimeMosaic',
    icon: 'fas fa-th',
  },
  {
    id: SLIDE_IDS.AIGCBench,
    name: 'AIGCBench',
    icon: 'fas fa-video',
  },
  {
    id: SLIDE_IDS.OKW,
    name: 'OKW',
    icon: 'fas fa-question-circle',
  },
  {
    id: SLIDE_IDS.PROJECTS,
    name: 'FolioSpace',
    icon: 'fas fa-layer-group',
  },
  {
    id: SLIDE_IDS.OVERVIEW,
    name: 'Overview',
    icon: 'fas fa-th-large',
  },
];
